# Generated by Django 3.1 on 2021-03-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_audiobookmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastmodel',
            name='uploaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='songmodel',
            name='uploaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
