# Generated by Django 3.1 on 2021-03-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210306_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobookmodel',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
