# Generated by Django 3.1 on 2021-03-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210306_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobookmodel',
            name='duration',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audiobookmodel',
            name='uploaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
